import type { Locale } from "@/types/api";

export type SettingGroup =
  "server" | "network" | "world" | "bases" | "rules" | "pvp" | "advanced";

export type SettingValue = string | number | boolean | string[];
export type SettingType =
  "text" | "password" | "integer" | "float" | "boolean" | "select" | "list";

interface LocalizedText {
  zh: string;
  en: string;
  ja?: string;
}

export interface SettingDefinition {
  key: string;
  group: SettingGroup;
  type: SettingType;
  defaultValue: SettingValue;
  label: LocalizedText;
  description: LocalizedText;
  min?: number;
  max?: number;
  step?: number;
  options?: readonly string[];
  listStyle?: "bare" | "quoted";
  unit?: LocalizedText;
  official?: boolean;
  restartRequired?: boolean;
}

export interface SettingGroupDefinition {
  id: SettingGroup;
  label: LocalizedText;
  description: LocalizedText;
}

const text = (zh: string, en: string, ja?: string): LocalizedText => ({
  zh,
  en,
  ja,
});

const setting = (
  key: string,
  group: SettingGroup,
  type: SettingType,
  defaultValue: SettingValue,
  labelZh: string,
  labelEn: string,
  descriptionZh: string,
  descriptionEn: string,
  options: Partial<SettingDefinition> = {},
): SettingDefinition => ({
  key,
  group,
  type,
  defaultValue,
  label: text(labelZh, labelEn),
  description: text(descriptionZh, descriptionEn),
  official: true,
  restartRequired: true,
  ...options,
});

export const SETTING_GROUPS: SettingGroupDefinition[] = [
  {
    id: "server",
    label: text("服务器", "Server"),
    description: text(
      "名称、密码、人数和日志行为",
      "Identity, passwords, capacity, and logging",
    ),
  },
  {
    id: "network",
    label: text("网络与 API", "Network & API"),
    description: text(
      "公共连接、REST API、RCON 和跨平台连接",
      "Public access, REST API, RCON, and crossplay",
    ),
  },
  {
    id: "world",
    label: text("世界倍率", "World rates"),
    description: text(
      "时间、经验、战斗、掉落和生存倍率",
      "Time, experience, combat, drops, and survival rates",
    ),
  },
  {
    id: "bases",
    label: text("基地与性能", "Bases & performance"),
    description: text(
      "基地上限、建筑、同步距离和对象数量",
      "Base limits, buildings, replication, and object budgets",
    ),
  },
  {
    id: "rules",
    label: text("世界规则", "World rules"),
    description: text(
      "传送、随机化、全局帕鲁箱和角色规则",
      "Travel, randomizer, Global Palbox, and character rules",
    ),
  },
  {
    id: "pvp",
    label: text("PvP 与硬核", "PvP & hardcore"),
    description: text(
      "伤害、死亡、重生和 PvP 专属掉落",
      "Damage, death, respawn, and PvP-specific drops",
    ),
  },
  {
    id: "advanced",
    label: text("高级兼容", "Advanced"),
    description: text(
      "默认 INI 中仍使用的兼容和底层参数",
      "Compatibility and lower-level parameters still used by the default INI",
    ),
  },
];

export const SETTING_DEFINITIONS: SettingDefinition[] = [
  setting(
    "ServerName",
    "server",
    "text",
    "Default Palworld Server",
    "服务器名称",
    "Server name",
    "服务器列表和连接界面显示的名称。",
    "Name shown in server listings and connection screens.",
  ),
  setting(
    "ServerDescription",
    "server",
    "text",
    "",
    "服务器描述",
    "Server description",
    "服务器说明文本。",
    "Description shown for the server.",
  ),
  setting(
    "ServerPassword",
    "server",
    "password",
    "",
    "服务器密码",
    "Server password",
    "玩家加入服务器时使用的密码。",
    "Password players must provide to join.",
  ),
  setting(
    "AdminPassword",
    "server",
    "password",
    "",
    "管理员密码",
    "Admin password",
    "用于获取管理员权限；启用 REST API 或 RCON 时必须设置强密码。",
    "Password used to obtain administrative privileges. Use a strong value when REST API or RCON is enabled.",
  ),
  setting(
    "ServerPlayerMaxNum",
    "server",
    "integer",
    32,
    "服务器玩家最大数量",
    "Maximum players",
    "可同时加入服务器的最大玩家数量。",
    "Maximum number of players who can join the server.",
    { min: 1, max: 512 },
  ),
  setting(
    "CoopPlayerMaxNum",
    "server",
    "integer",
    4,
    "合作玩家最大数量",
    "Maximum co-op players",
    "合作模式允许的最大玩家数量。专用服务器总人数由 ServerPlayerMaxNum 控制。",
    "Maximum players allowed in a co-op session. Dedicated-server capacity is controlled by ServerPlayerMaxNum.",
    { min: 1, max: 4, official: false },
  ),
  setting(
    "bIsUseBackupSaveData",
    "server",
    "boolean",
    true,
    "是否自动备份存档数据",
    "Enable world backups",
    "启用游戏自身的世界备份，会增加磁盘写入。",
    "Enable game-managed world backups. This increases disk load.",
  ),
  setting(
    "AutoSaveSpan",
    "server",
    "float",
    30,
    "自动保存间隔",
    "Auto-save interval",
    "游戏自动保存世界的间隔。",
    "Interval between automatic world saves.",
    {
      min: 30,
      max: 3600,
      step: 1,
      unit: text("秒", "seconds"),
      official: false,
    },
  ),
  setting(
    "LogFormatType",
    "server",
    "select",
    "Text",
    "日志格式类型",
    "Log format",
    "服务器日志输出为文本或 JSON。",
    "Write server logs as text or JSON.",
    { options: ["Text", "Json"] },
  ),
  setting(
    "ChatPostLimitPerMinute",
    "server",
    "integer",
    10,
    "每分钟聊天限制数",
    "Chat limit per minute",
    "单个玩家每分钟允许发送的聊天消息数量。",
    "Maximum chat messages allowed per player per minute.",
    { min: 0, max: 100 },
  ),
  setting(
    "bIsShowJoinLeftMessage",
    "server",
    "boolean",
    true,
    "显示玩家加入/离开消息",
    "Show join/leave messages",
    "在游戏内显示玩家加入和离开服务器的消息。",
    "Show in-game messages when players join or leave.",
  ),
  setting(
    "bShowPlayerList",
    "server",
    "boolean",
    false,
    "启用服务器内可以查看其他玩家列表",
    "Show player list",
    "在 ESC 菜单中启用在线玩家列表。",
    "Enable the player list in the ESC menu.",
  ),

  setting(
    "PublicIP",
    "network",
    "text",
    "",
    "公共 IP",
    "Public IP",
    "社区服务器对外公布的公网 IP；留空时由服务器环境决定。",
    "External public IP advertised by a community server. Leave blank for automatic behavior.",
  ),
  setting(
    "PublicPort",
    "network",
    "integer",
    8211,
    "公共端口",
    "Public port",
    "社区服务器对外公布的端口；不会修改实际监听端口。",
    "External port advertised by a community server. This does not change the listening port.",
    { min: 1, max: 65535 },
  ),
  setting(
    "RCONEnabled",
    "network",
    "boolean",
    false,
    "启用 RCON",
    "Enable RCON",
    "启用官方 RCON 管理接口。请仅向受信任网络开放。",
    "Enable the official RCON management interface. Expose it only to trusted networks.",
  ),
  setting(
    "RCONPort",
    "network",
    "integer",
    25575,
    "RCON 端口",
    "RCON port",
    "官方 RCON 接口的监听端口。",
    "Listening port for the official RCON interface.",
    { min: 1, max: 65535 },
  ),
  setting(
    "CrossplayPlatforms",
    "network",
    "list",
    ["Steam", "Xbox", "PS5", "Mac"],
    "允许连接平台",
    "Crossplay platforms",
    "官方当前使用的跨平台白名单，替代已不可用的 AllowConnectPlatform。",
    "Current official platform allowlist. Replaces the unavailable AllowConnectPlatform setting.",
    { options: ["Steam", "Xbox", "PS5", "Mac"], listStyle: "bare" },
  ),
  setting(
    "RESTAPIEnabled",
    "network",
    "boolean",
    false,
    "启用 REST API",
    "Enable REST API",
    "启用官方 REST API。建议仅在受信任网络中开放。",
    "Enable the official REST API. Expose it only to trusted networks.",
  ),
  setting(
    "RESTAPIPort",
    "network",
    "integer",
    8212,
    "REST API 端口",
    "REST API port",
    "官方 REST API 的监听端口。",
    "Listening port for the official REST API.",
    { min: 1, max: 65535 },
  ),
  setting(
    "bUseAuth",
    "network",
    "boolean",
    true,
    "使用授权",
    "Use platform authentication",
    "启用服务器平台认证。",
    "Enable platform authentication for the server.",
    { official: false },
  ),
  setting(
    "bAllowClientMod",
    "network",
    "boolean",
    true,
    "允许客户端Mod",
    "Allow client mods",
    "允许启用了模组的客户端加入。",
    "Allow clients with mods enabled to join.",
  ),
  setting(
    "BanListURL",
    "network",
    "text",
    "https://b.palworldgame.com/api/banlist.txt",
    "封禁列表 URL",
    "Ban list URL",
    "服务器使用的官方远程封禁列表地址。",
    "Official remote ban list URL used by the server.",
    { official: false },
  ),
  setting(
    "Region",
    "network",
    "text",
    "",
    "地区",
    "Region",
    "服务器列表使用的区域标识。",
    "Region identifier used by server listings.",
    { official: false },
  ),

  setting(
    "Difficulty",
    "world",
    "select",
    "None",
    "难度",
    "Difficulty preset",
    "自定义服务器通常保持 None，并使用下方倍率。",
    "Custom servers normally keep None and use the individual rates below.",
    { options: ["None"], official: false },
  ),
  setting(
    "DayTimeSpeedRate",
    "world",
    "float",
    1,
    "白天流逝速度",
    "Daytime speed",
    "白天时间推进倍率。",
    "Daytime progression speed multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "NightTimeSpeedRate",
    "world",
    "float",
    1,
    "夜间流逝速度",
    "Nighttime speed",
    "夜晚时间推进倍率。",
    "Nighttime progression speed multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "ExpRate",
    "world",
    "float",
    1,
    "经验值倍率",
    "Experience rate",
    "玩家与帕鲁获得经验的倍率。",
    "Experience gain multiplier.",
    { min: 0, max: 20, step: 0.1 },
  ),
  setting(
    "PalCaptureRate",
    "world",
    "float",
    1,
    "捕捉概率倍率",
    "Capture rate",
    "帕鲁捕获成功率倍率。",
    "Pal capture rate multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PalSpawnNumRate",
    "world",
    "float",
    1,
    "帕鲁出现数量倍率",
    "Pal spawn rate",
    "野生帕鲁数量倍率；较高值会明显增加服务器负载。",
    "Wild Pal spawn multiplier. High values significantly increase server load.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PalDamageRateAttack",
    "world",
    "float",
    1,
    "帕鲁攻击伤害倍率",
    "Pal damage dealt",
    "帕鲁造成伤害的倍率。",
    "Damage dealt by Pals multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PalDamageRateDefense",
    "world",
    "float",
    1,
    "帕鲁承受伤害倍率",
    "Pal damage taken",
    "帕鲁受到伤害的倍率。",
    "Damage taken by Pals multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PlayerDamageRateAttack",
    "world",
    "float",
    1,
    "玩家攻击伤害倍率",
    "Player damage dealt",
    "玩家造成伤害的倍率。",
    "Damage dealt by players multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PlayerDamageRateDefense",
    "world",
    "float",
    1,
    "玩家承受伤害倍率",
    "Player damage taken",
    "玩家受到伤害的倍率。",
    "Damage taken by players multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PlayerStomachDecreaceRate",
    "world",
    "float",
    1,
    "玩家饱食度降低倍率",
    "Player hunger depletion",
    "玩家饱食度消耗倍率。",
    "Player hunger depletion multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PlayerStaminaDecreaceRate",
    "world",
    "float",
    1,
    "玩家耐力降低倍率",
    "Player stamina depletion",
    "玩家耐力消耗倍率。",
    "Player stamina depletion multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PlayerAutoHPRegeneRate",
    "world",
    "float",
    1,
    "玩家生命值自然回复倍率",
    "Player HP regeneration",
    "玩家自然生命恢复倍率。",
    "Player natural HP regeneration multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PlayerAutoHpRegeneRateInSleep",
    "world",
    "float",
    1,
    "玩家睡眠时生命值回复倍率",
    "Player sleep regeneration",
    "玩家睡眠时生命恢复倍率。",
    "Player HP regeneration while sleeping.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PalStomachDecreaceRate",
    "world",
    "float",
    1,
    "帕鲁饱食度降低倍率",
    "Pal hunger depletion",
    "帕鲁饱食度消耗倍率。",
    "Pal hunger depletion multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PalStaminaDecreaceRate",
    "world",
    "float",
    1,
    "帕鲁耐力降低倍率",
    "Pal stamina depletion",
    "帕鲁耐力消耗倍率。",
    "Pal stamina depletion multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PalAutoHPRegeneRate",
    "world",
    "float",
    1,
    "帕鲁生命值自然回复倍率",
    "Pal HP regeneration",
    "帕鲁自然生命恢复倍率。",
    "Pal natural HP regeneration multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PalAutoHpRegeneRateInSleep",
    "world",
    "float",
    1,
    "帕鲁睡眠时/终端中生命值回复倍率",
    "Palbox HP regeneration",
    "帕鲁睡眠或位于帕鲁箱时的生命恢复倍率。",
    "Pal HP regeneration while sleeping or in the Palbox.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "EnemyDropItemRate",
    "world",
    "float",
    1,
    "道具掉落量倍率",
    "Enemy drop rate",
    "敌人掉落物品数量倍率。",
    "Enemy item drop quantity multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PalEggDefaultHatchingTime",
    "world",
    "float",
    72,
    "巨大蛋孵化所需时间(小时)",
    "Huge egg hatch time",
    "孵化巨大蛋所需小时数，其他蛋按比例计算。",
    "Hours required to hatch a Huge Egg; other eggs scale from this value.",
    { min: 0, max: 240, step: 1, unit: text("小时", "hours") },
  ),
  setting(
    "WorkSpeedRate",
    "world",
    "float",
    1,
    "工作速率",
    "Work speed rate",
    "帕鲁工作速度倍率。",
    "Pal work speed multiplier.",
    { min: 0.1, max: 5, step: 0.1, official: false },
  ),
  setting(
    "MonsterFarmActionSpeedRate",
    "world",
    "float",
    1,
    "帕鲁放牧产出物品速度倍率",
    "Ranch production speed",
    "帕鲁在牧场生产物品的速度倍率。",
    "Item production speed multiplier for grazing Pals.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "ItemWeightRate",
    "world",
    "float",
    1,
    "物品重量倍率",
    "Item weight rate",
    "物品重量倍率。",
    "Item weight multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "ItemCorruptionMultiplier",
    "world",
    "float",
    1,
    "物品腐化倍率",
    "Item corruption rate",
    "可腐败物品的腐败速度倍率。",
    "Corruption speed multiplier for perishable items.",
    { min: 0.1, max: 10, step: 0.1 },
  ),
  setting(
    "EquipmentDurabilityDamageRate",
    "world",
    "float",
    1,
    "装备耐久度损坏率",
    "Durability loss rate",
    "装备耐久损耗倍率。",
    "Equipment durability loss multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "SupplyDropSpan",
    "world",
    "integer",
    180,
    "陨石或空投的间隔（分钟）",
    "Meteorite / supply interval",
    "陨石和补给投放的间隔。",
    "Meteorite and supply drop interval.",
    { min: 0, max: 1440, unit: text("分钟", "minutes") },
  ),

  setting(
    "BaseCampMaxNum",
    "bases",
    "integer",
    128,
    "全地图据点最大数量",
    "Server base limit",
    "整个服务器允许存在的基地总数。",
    "Total number of bases allowed across the server.",
    { min: 0, max: 10240 },
  ),
  setting(
    "BaseCampMaxNumInGuild",
    "bases",
    "integer",
    4,
    "公会的据点最大数量",
    "Bases per guild",
    "每个公会允许的基地数；官方默认 4，最大 10。",
    "Maximum bases per guild. Official default is 4 and maximum is 10.",
    { min: 1, max: 10 },
  ),
  setting(
    "BaseCampWorkerMaxNum",
    "bases",
    "integer",
    15,
    "可分配至据点工作的帕鲁数量上限",
    "Workers per base",
    "单个基地可部署的帕鲁数量，最大 50；提高会增加负载。",
    "Maximum Pals assigned per base, up to 50. Higher values increase load.",
    { min: 1, max: 50 },
  ),
  setting(
    "MaxBuildingLimitNum",
    "bases",
    "integer",
    0,
    "每个玩家的建筑物最大数量",
    "Buildings per player",
    "每名玩家的建筑数量上限，0 表示不限制。",
    "Per-player building cap. Zero means unlimited.",
    { min: 0, max: 100000 },
  ),
  setting(
    "BuildObjectHpRate",
    "bases",
    "float",
    1,
    "建筑物生命值倍率",
    "Building HP rate",
    "建筑生命值倍率。",
    "Building health multiplier.",
    { min: 0.1, max: 5, step: 0.1, official: false },
  ),
  setting(
    "BuildObjectDamageRate",
    "bases",
    "float",
    1,
    "对建筑物伤害倍率",
    "Building damage rate",
    "建筑受到伤害的倍率。",
    "Damage dealt to buildings multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "BuildObjectDeteriorationDamageRate",
    "bases",
    "float",
    1,
    "非基地圈内建筑物的劣化速度倍率",
    "Building decay rate",
    "建筑自然衰减伤害倍率；0 可关闭衰减。",
    "Building deterioration multiplier. Set to zero to disable decay.",
    { min: 0, max: 10, step: 0.1 },
  ),
  setting(
    "CollectionDropRate",
    "bases",
    "float",
    1,
    "道具采集量倍率",
    "Gatherable drop rate",
    "采集对象掉落数量倍率。",
    "Gatherable item quantity multiplier.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "CollectionObjectHpRate",
    "bases",
    "float",
    1,
    "可采集物品生命值倍率",
    "Gatherable object HP",
    "矿石、树木等采集对象的生命倍率。",
    "Health multiplier for gatherable objects.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "CollectionObjectRespawnSpeedRate",
    "bases",
    "float",
    1,
    "可采集物品重生间隔倍率",
    "Gatherable respawn rate",
    "采集对象重生间隔倍率。",
    "Respawn interval multiplier for gatherable objects.",
    { min: 0.1, max: 5, step: 0.1 },
  ),
  setting(
    "PhysicsActiveDropItemMaxNum",
    "bases",
    "integer",
    -1,
    "可启用物理模拟的掉落物最大数量",
    "Physics drop limit",
    "可同时启用物理行为的掉落物数量上限，-1 使用游戏默认策略。",
    "Maximum dropped items that may use physics behavior. Use -1 for the game default policy.",
    { min: -1, max: 10000 },
  ),
  setting(
    "ItemContainerForceMarkDirtyInterval",
    "bases",
    "float",
    1,
    "物品容器强制标记为脏的间隔（秒）",
    "Container resync interval",
    "容器界面打开时强制重新同步的间隔。",
    "Forced resync interval while a container UI is open.",
    { min: 0.1, max: 60, step: 0.1, unit: text("秒", "seconds") },
  ),
  setting(
    "ServerReplicatePawnCullDistance",
    "bases",
    "float",
    15000,
    "玩家与帕鲁同步距离",
    "Pal replication distance",
    "帕鲁与玩家之间的同步距离，官方范围 5000 至 15000 厘米。",
    "Pal replication distance from players. Official range is 5000 to 15000 cm.",
    { min: 5000, max: 15000, step: 100, unit: text("厘米", "cm") },
  ),

  setting(
    "DeathPenalty",
    "rules",
    "select",
    "All",
    "死亡惩罚",
    "Death penalty",
    "None 不掉落；Item 掉落非装备物品；ItemAndEquipment 掉落全部物品；All 还会掉落队伍帕鲁。",
    "None drops nothing; Item drops non-equipment items; ItemAndEquipment drops all items; All also drops party Pals.",
    { options: ["None", "Item", "ItemAndEquipment", "All"] },
  ),
  setting(
    "bEnableInvaderEnemy",
    "rules",
    "boolean",
    true,
    "启用袭击事件",
    "Enable invasions",
    "启用基地入侵敌人事件。",
    "Enable enemy invasion events.",
  ),
  setting(
    "EnablePredatorBossPal",
    "rules",
    "boolean",
    true,
    "启用猛兽 Boss 帕鲁",
    "Enable Predator Boss Pals",
    "启用世界中的猛兽 Boss 帕鲁。",
    "Enable Predator Boss Pals in the world.",
    { official: false },
  ),
  setting(
    "bEnableFastTravel",
    "rules",
    "boolean",
    true,
    "启用快速传送",
    "Enable fast travel",
    "允许使用快速传送。",
    "Allow fast travel.",
  ),
  setting(
    "bEnableFastTravelOnlyBaseCamp",
    "rules",
    "boolean",
    false,
    "仅基地可快速旅行",
    "Base-only fast travel",
    "把快速传送限制为基地之间。",
    "Restrict fast travel to travel between bases.",
  ),
  setting(
    "bIsStartLocationSelectByMap",
    "rules",
    "boolean",
    true,
    "是否通过地图选择复活位置",
    "Select start location",
    "允许新角色在地图上选择出生位置。",
    "Allow new characters to choose a starting location on the map.",
  ),
  setting(
    "bExistPlayerAfterLogout",
    "rules",
    "boolean",
    false,
    "登出后玩家人物是否存在",
    "Keep players after logout",
    "玩家离线后在当前位置进入睡眠状态。",
    "Keep logged-out players sleeping at their current location.",
  ),
  setting(
    "bEnableNonLoginPenalty",
    "rules",
    "boolean",
    true,
    "启用超时未登录惩罚",
    "Enable non-login penalty",
    "启用玩家长期不登录相关惩罚。",
    "Enable penalties related to extended player absence.",
    { official: false },
  ),
  setting(
    "RandomizerType",
    "rules",
    "select",
    "None",
    "随机器类型",
    "Pal randomizer mode",
    "None 关闭；Region 按区域随机；All 完全随机。",
    "None disables randomization; Region randomizes per area; All fully randomizes.",
    { options: ["None", "Region", "All"] },
  ),
  setting(
    "RandomizerSeed",
    "rules",
    "text",
    "",
    "随机种子",
    "Randomizer seed",
    "启用帕鲁随机化时使用的种子。",
    "Seed used when Pal spawn randomization is enabled.",
  ),
  setting(
    "bIsRandomizerPalLevelRandom",
    "rules",
    "boolean",
    false,
    "完全随机野外帕鲁等级",
    "Fully random Pal levels",
    "开启后野生帕鲁等级完全随机；关闭时在区域预期范围内随机。",
    "Fully randomize wild Pal levels instead of using each area's intended range.",
  ),
  setting(
    "bAllowGlobalPalboxExport",
    "rules",
    "boolean",
    true,
    "允许通过跨界帕鲁终端保存帕鲁的基因序列",
    "Allow Global Palbox export",
    "允许玩家把帕鲁保存到全局帕鲁箱。",
    "Allow saving Pals to the Global Palbox.",
  ),
  setting(
    "bAllowGlobalPalboxImport",
    "rules",
    "boolean",
    false,
    "允许通过跨界帕鲁终端的基因序列复原帕鲁",
    "Allow Global Palbox import",
    "允许玩家从全局帕鲁箱载入帕鲁。",
    "Allow loading Pals from the Global Palbox.",
  ),
  setting(
    "DenyTechnologyList",
    "rules",
    "list",
    [],
    "禁止科技列表",
    "Denied technologies",
    "禁止解锁的 Technology ID 列表，例如 PALBOX、RepairBench。",
    "Technology IDs that cannot be unlocked, for example PALBOX and RepairBench.",
    { listStyle: "quoted" },
  ),
  setting(
    "bEnableBuildingPlayerUIdDisplay",
    "rules",
    "boolean",
    false,
    "显示建筑建造者玩家ID",
    "Show building creator ID",
    "在建筑上显示创建者的玩家 ID。",
    "Display the creator's player ID on structures.",
  ),
  setting(
    "bEnableVoiceChat",
    "rules",
    "boolean",
    false,
    "启用游戏内语音聊天",
    "Enable voice chat",
    "启用游戏内语音聊天。",
    "Enable in-game voice chat.",
  ),
  setting(
    "VoiceChatMaxVolumeDistance",
    "rules",
    "float",
    3000,
    "语音音量无衰减距离",
    "Voice chat full-volume distance",
    "在此距离内语音不会衰减。",
    "Distance within which voice chat volume does not attenuate.",
    { min: 100, max: 50000, step: 100, unit: text("厘米", "cm") },
  ),
  setting(
    "VoiceChatZeroVolumeDistance",
    "rules",
    "float",
    15000,
    "语音完全静音距离",
    "Voice chat zero-volume distance",
    "达到此距离后语音音量降为零。",
    "Distance at which voice chat volume reaches zero.",
    { min: 100, max: 50000, step: 100, unit: text("厘米", "cm") },
  ),
  setting(
    "bAllowEnhanceStat_Health",
    "rules",
    "boolean",
    true,
    "允许加点-生命",
    "Allow HP stat allocation",
    "允许把属性点分配到生命值。",
    "Allow allocating stat points to HP.",
  ),
  setting(
    "bAllowEnhanceStat_Attack",
    "rules",
    "boolean",
    true,
    "允许加点-攻击",
    "Allow Attack allocation",
    "允许把属性点分配到攻击。",
    "Allow allocating stat points to Attack.",
  ),
  setting(
    "bAllowEnhanceStat_Stamina",
    "rules",
    "boolean",
    true,
    "允许加点-体力",
    "Allow Stamina allocation",
    "允许把属性点分配到耐力。",
    "Allow allocating stat points to Stamina.",
  ),
  setting(
    "bAllowEnhanceStat_Weight",
    "rules",
    "boolean",
    true,
    "允许加点-负重",
    "Allow Weight allocation",
    "允许把属性点分配到负重。",
    "Allow allocating stat points to Carry Weight.",
  ),
  setting(
    "bAllowEnhanceStat_WorkSpeed",
    "rules",
    "boolean",
    true,
    "允许加点-工作速度",
    "Allow Work Speed allocation",
    "允许把属性点分配到工作速度。",
    "Allow allocating stat points to Work Speed.",
  ),

  setting(
    "bIsPvP",
    "pvp",
    "boolean",
    false,
    "是否 PvP",
    "Enable PvP",
    "启用玩家对战规则。",
    "Enable player-versus-player rules.",
  ),
  setting(
    "bEnablePlayerToPlayerDamage",
    "pvp",
    "boolean",
    false,
    "启用玩家对玩家伤害",
    "Enable player damage",
    "允许玩家对其他玩家造成伤害。",
    "Allow players to damage other players.",
    { official: false },
  ),
  setting(
    "bEnableFriendlyFire",
    "pvp",
    "boolean",
    false,
    "启用友伤",
    "Enable friendly fire",
    "允许对友方造成伤害。",
    "Allow damage to friendly players and allies.",
    { official: false },
  ),
  setting(
    "bHardcore",
    "pvp",
    "boolean",
    false,
    "是否硬核模式",
    "Enable hardcore",
    "角色死亡后无法正常复活。启用前应先测试规则。",
    "Characters cannot normally respawn after death. Test the rules before enabling.",
  ),
  setting(
    "bPalLost",
    "pvp",
    "boolean",
    false,
    "是否帕鲁丢失模式",
    "Permanently lose Pals",
    "死亡时永久失去帕鲁。",
    "Permanently lose Pals on death.",
  ),
  setting(
    "bCharacterRecreateInHardcore",
    "pvp",
    "boolean",
    false,
    "是否允许在硬核模式下重新创建角色",
    "Recreate character in hardcore",
    "硬核模式死亡后允许重新创建角色。",
    "Allow character recreation after death in hardcore mode.",
  ),
  setting(
    "bCanPickupOtherGuildDeathPenaltyDrop",
    "pvp",
    "boolean",
    false,
    "能否拾取其他公会玩家的死亡惩罚掉落物",
    "Pick up other guild drops",
    "允许拾取其他公会玩家的死亡惩罚掉落。",
    "Allow pickup of death-penalty drops from other guilds.",
    { official: false },
  ),
  setting(
    "bEnableDefenseOtherGuildPlayer",
    "pvp",
    "boolean",
    false,
    "启用据点内防御其他公会玩家",
    "Defend against other guilds",
    "启用对其他公会玩家的防御规则。",
    "Enable defense behavior against players from other guilds.",
    { official: false },
  ),
  setting(
    "bInvisibleOtherGuildBaseCampAreaFX",
    "pvp",
    "boolean",
    false,
    "隐藏其他公会据点区域特效",
    "Hide other guild base areas",
    "控制其他公会基地范围效果的显示。",
    "Control visibility of other guild base-area effects.",
  ),
  setting(
    "bBuildAreaLimit",
    "pvp",
    "boolean",
    false,
    "建筑区域限制",
    "Restrict building areas",
    "禁止在传送点等特殊建筑附近建造。",
    "Prevent building near structures such as fast-travel points.",
  ),
  setting(
    "bDisplayPvPItemNumOnWorldMap_BaseCamp",
    "pvp",
    "boolean",
    false,
    "地图显示PVP掉落物数量（基地）",
    "Show base PvP items",
    "在地图上显示各基地的 PvP 专属物品数量。",
    "Show PvP-exclusive item counts for bases on the map.",
  ),
  setting(
    "bDisplayPvPItemNumOnWorldMap_Player",
    "pvp",
    "boolean",
    false,
    "地图显示PVP掉落物数量（玩家）",
    "Show player PvP items",
    "在地图上显示玩家位置和 PvP 专属物品数量。",
    "Show player locations and PvP-exclusive item counts on the map.",
  ),
  setting(
    "bAdditionalDropItemWhenPlayerKillingInPvPMode",
    "pvp",
    "boolean",
    false,
    "启用PVP击杀附加掉落",
    "Enable PvP bonus drop",
    "玩家在 PvP 中被击杀时追加指定物品。",
    "Drop a configured bonus item when a player is killed in PvP.",
  ),
  setting(
    "AdditionalDropItemWhenPlayerKillingInPvPMode",
    "pvp",
    "text",
    "",
    "PVP击杀附加掉落物",
    "PvP bonus item ID",
    "PvP 击杀时追加掉落的物品 ID。",
    "Item ID dropped as the PvP kill bonus.",
  ),
  setting(
    "AdditionalDropItemNumWhenPlayerKillingInPvPMode",
    "pvp",
    "integer",
    1,
    "PVP击杀附加掉落物数量",
    "PvP bonus item count",
    "PvP 击杀追加物品的数量。",
    "Quantity of the PvP bonus item.",
    { min: 0, max: 10000 },
  ),
  setting(
    "BlockRespawnTime",
    "pvp",
    "float",
    5,
    "阻止重生时间",
    "Respawn cooldown",
    "死亡后允许重生前的基础冷却时间。",
    "Base cooldown before respawning after death.",
    { min: 0, max: 3600, step: 1, unit: text("秒", "seconds") },
  ),
  setting(
    "RespawnPenaltyDurationThreshold",
    "pvp",
    "float",
    0,
    "重生惩罚持续时间阈值",
    "Respawn penalty threshold",
    "存活超过该秒数后，下次死亡应用 RespawnPenaltyTimeScale。",
    "Survival threshold before the next death applies RespawnPenaltyTimeScale.",
    { min: 0, max: 86400, step: 1, unit: text("秒", "seconds") },
  ),
  setting(
    "RespawnPenaltyTimeScale",
    "pvp",
    "float",
    2,
    "重生惩罚时间倍数",
    "Respawn cooldown multiplier",
    "满足生存阈值后的重生冷却倍率。",
    "Respawn cooldown multiplier after the survival threshold is met.",
    { min: 0, max: 100, step: 0.1 },
  ),

  setting(
    "DropItemMaxNum",
    "advanced",
    "integer",
    3000,
    "掉落物品最大存在数量",
    "World drop limit",
    "世界中保留的普通掉落物数量上限。",
    "Maximum ordinary dropped items retained in the world.",
    { min: 0, max: 100000, official: false },
  ),
  setting(
    "DropItemMaxNum_UNKO",
    "advanced",
    "integer",
    100,
    "帕鲁便便掉落最大数量",
    "Special drop limit",
    "特殊掉落对象的数量上限。",
    "Maximum number of special dropped objects.",
    { min: 0, max: 10000, official: false },
  ),
  setting(
    "DropItemAliveMaxHours",
    "advanced",
    "float",
    1,
    "掉落物品存活最大小时数",
    "Drop lifetime",
    "世界掉落物保留的最长时间。",
    "Maximum lifetime of dropped items.",
    {
      min: 0,
      max: 240,
      step: 0.5,
      unit: text("小时", "hours"),
      official: false,
    },
  ),
  setting(
    "bAutoResetGuildNoOnlinePlayers",
    "advanced",
    "boolean",
    false,
    "自动重置无在线玩家的公会",
    "Auto-reset offline guilds",
    "公会所有成员长期不在线时自动删除建筑和基地帕鲁。",
    "Delete structures and base Pals when no guild members log in.",
  ),
  setting(
    "AutoResetGuildTimeNoOnlinePlayers",
    "advanced",
    "float",
    72,
    "自动重置无在线玩家的公会时间(小时)",
    "Offline guild reset threshold",
    "触发自动清理前允许公会无人在线的时长。",
    "Offline duration before automatic guild reset is triggered.",
    { min: 0, max: 10000, step: 1, unit: text("小时", "hours") },
  ),
  setting(
    "GuildPlayerMaxNum",
    "advanced",
    "integer",
    20,
    "公会玩家最大数量",
    "Guild member limit",
    "每个公会允许的最大成员数量。",
    "Maximum number of players in a guild.",
    { min: 1, max: 1000 },
  ),
  setting(
    "GuildRejoinCooldownMinutes",
    "advanced",
    "integer",
    0,
    "公会重加冷却时间(分钟)",
    "Guild rejoin cooldown",
    "退出公会后重新加入公会的冷却时间。",
    "Cooldown before a player may rejoin a guild.",
    { min: 0, max: 10080, unit: text("分钟", "minutes") },
  ),
  setting(
    "PlayerDataPalStorageUpdateCheckTickInterval",
    "advanced",
    "float",
    1,
    "玩家帕鲁仓库数据更新检测间隔",
    "Pal storage update interval",
    "检查玩家帕鲁仓库数据更新的间隔。",
    "Interval for checking player Pal storage data updates.",
    {
      min: 0.1,
      max: 60,
      step: 0.1,
      unit: text("秒", "seconds"),
      official: false,
    },
  ),
  setting(
    "AutoTransferMasterCheckIntervalSeconds",
    "advanced",
    "float",
    3600,
    "公会归属自动转移检测间隔(秒)",
    "Guild master transfer check",
    "检查公会会长是否满足自动移交条件的间隔。",
    "Interval for checking guild-master auto-transfer eligibility.",
    {
      min: 60,
      max: 86400,
      step: 60,
      unit: text("秒", "seconds"),
      official: false,
    },
  ),
  setting(
    "AutoTransferMasterThresholdDays",
    "advanced",
    "integer",
    14,
    "公会会长自动移交离线天数阈值",
    "Guild master offline threshold",
    "公会会长离线达到该天数后允许自动移交。",
    "Days the guild master must be offline before automatic transfer.",
    { min: 1, max: 365, unit: text("天", "days"), official: false },
  ),
  setting(
    "MaxGuildsPerFrame",
    "advanced",
    "integer",
    10,
    "单帧处理公会最大数量",
    "Guilds processed per frame",
    "服务器每帧处理的最大公会数量。",
    "Maximum number of guilds processed per frame.",
    { min: 1, max: 100, official: false },
  ),
  setting(
    "BuildingNameDisplayCacheTTLSeconds",
    "advanced",
    "integer",
    60,
    "建筑名称显示缓存有效期(秒)",
    "Building name cache TTL",
    "建筑名称显示缓存的有效时间。",
    "TTL for the building-name display cache.",
    { min: 1, max: 3600, unit: text("秒", "seconds"), official: false },
  ),
  setting(
    "bIsMultiplay",
    "advanced",
    "boolean",
    false,
    "是否多人游戏",
    "Multiplayer flag",
    "底层多人模式标志，专用服务器通常由启动方式控制。",
    "Low-level multiplayer flag normally controlled by the dedicated server launch mode.",
    { official: false },
  ),
  setting(
    "bActiveUNKO",
    "advanced",
    "boolean",
    false,
    "激活帕鲁便便",
    "Enable special drops",
    "兼容旧默认配置的特殊掉落选项。",
    "Compatibility option retained from the default configuration.",
    { official: false },
  ),
  setting(
    "bEnableAimAssistPad",
    "advanced",
    "boolean",
    true,
    "启用手柄瞄准辅助",
    "Controller aim assist",
    "为手柄玩家启用辅助瞄准。",
    "Enable aim assist for controller players.",
    { official: false },
  ),
  setting(
    "bEnableAimAssistKeyboard",
    "advanced",
    "boolean",
    false,
    "启用键盘瞄准辅助",
    "Keyboard aim assist",
    "为键盘鼠标玩家启用辅助瞄准。",
    "Enable aim assist for keyboard and mouse players.",
    { official: false },
  ),
];

export const SETTING_BY_KEY = new Map(
  SETTING_DEFINITIONS.map((definition) => [definition.key, definition]),
);

export function getLocalizedText(value: LocalizedText, locale: Locale) {
  return value[locale] ?? value.en;
}

export function getDefaultSettings() {
  return Object.fromEntries(
    SETTING_DEFINITIONS.map((definition) => [
      definition.key,
      Array.isArray(definition.defaultValue)
        ? [...definition.defaultValue]
        : definition.defaultValue,
    ]),
  ) as Record<string, SettingValue>;
}
